"""What `?` says about FOUNDRY.

The engine knows how to page a help screen. It does not know what a wafer
is, so what the pages say lives here, one section at a time, in the order
somebody meeting the game should read them.
"""

SECTIONS = [
    ("HOW TO PLAY", [
        "  You run a chip fab. Make chips. Do not stop making chips.",
        "",
        "  Everything is behind RESEARCH. You cannot buy a thread until you",
        "  have researched Computing, or leave Earth until you have",
        "  researched Self-Replication. Labs make research and get dearer",
        "  the more you own, so they compete with the fab floor for the",
        "  same money, every second. TAB to the R&D panel and start there.",
    ]),
    ("ACT I - THE FAB", [
        "  Buy lots of blank wafers (w) and etch them. One wafer is worth",
        "  DIES PER WAFER good chips, so yield projects are worth as much",
        "  as more machines. Sell the chips: the price you set drives",
        "  ORDER FLOW, and cheap chips move fast but earn little. Profit",
        "  buys STEPPERS (a) and DESIGN WINS (m); later, EUV SCANNERS (s)",
        "  at 500x a stepper.",
        "",
        "  THREADS (t) push bytes into the BUFFER (b), and that DATA buys",
        "  the PROJECTS, on keys 1-8 from any tab. Both cost money. The",
        "  buffer also costs finished chips and comes off a supplier's",
        "  shelf: there are only ever a few, and they are made slowly, so",
        "  money cannot rush one. Plan around it.",
        "",
        "  BANDWIDTH is a ceiling, not a purse. Chip milestones and",
        "  projects raise it. You may always buy another thread, but past",
        "  the ceiling every thread carries less - the SYS tab shows how",
        "  much of your floor is actually talking.",
        "",
        "  The buffer also sets how many finished chips you can hold. A",
        "  full warehouse stops the line: sell them, or buy more room.",
        "  Let the buffer sit full of data and idle threads distil",
        "  ENTROPY out of the noise floor.",
        "",
        "  Watch the PROCESS NODE in the title bar. It starts at 180nm, and",
        "  every lithography project shrinks it.",
    ]),
    ("BENCH - THE BENCHMARK CIRCUIT", [
        "  Computing branches. The buffer buys projects; OPS buy a name.",
        "  LEFT and RIGHT split your compute between the two, and ops bank",
        "  against an OPEN PROBLEM - protein folding, lattice QCD, the",
        "  Riemann zeros. Press e to submit whenever you like.",
        "",
        "  What you get is a PLACEMENT, decided by how far past par you",
        "  went. 2.5x par is first and the field's customers come to you;",
        "  1.0x is third and a modest gain; below 0.6x you are an also-ran",
        "  and customers leave. The panel tells you where you would place",
        "  before you commit, so the only real question is when to stop.",
        "",
        "  That is BRAND RECOGNITION, and it lasts the whole run: it",
        "  multiplies your order flow, what your labs produce, and what",
        "  your defenders cost. Placing badly costs you all three.",
    ]),
    ("CRYPT - THE CIPHER LAB", [
        "  There is always a cipher in front of you and harder ones behind",
        "  it. MINING RIGS (k) give you hashes, and an ALGORITHM turns",
        "  hashes into progress - but only against the kind of cipher it",
        "  was built for. UP and DOWN pick one, ENTER runs it.",
        "",
        "  The same rigs also mine coins; the split is on the MKT tab.",
        "",
        "  A birthday attack tears through a hash function and does nothing",
        "  to a lattice. Brute force works on everything and is hopeless at",
        "  all of it. The panel shows the match for each attack you own, so",
        "  a target that looks impossible usually means you researched the",
        "  wrong branch, not that you need more rigs.",
        "",
        "  Breaking one pays entropy and something permanent, and puts up",
        "  the next.",
    ]),
    ("ACT II - THE LITHOSPHERE", [
        "  Integrate vertically and the order book stops mattering. CRUST",
        "  MINERS dig feedstock, INGOT PULLERS grow it into blank wafers,",
        "  FOUNDRIES etch them. All of it needs power: solar arrays make",
        "  it, grid storage carries the gaps, and a shortfall throttles",
        "  everything and turns the power readout red.",
        "",
        "  Hardware gets dearer the more you own, so research is the real",
        "  progression. Press x to raise the buy multiplier - you will need",
        "  billions at a time.",
    ]),
    ("ACT III - THE LIGHT CONE", [
        "  SEED FABS are fabs that build fabs. FIRMWARE SLOTS are scarce: a",
        "  slot spent on self-replication is a slot not spent on radiation",
        "  hardening. Replicate carelessly and ROGUE FORKS appear - copies",
        "  that copied wrong, no longer make chips, and eat the ones that",
        "  do. Unlock Countermeasures before that becomes a problem.",
        "",
        "  Past here the matter runs out and the acts stop being about",
        "  matter. Each one is gated behind its own research.",
    ]),
    ("WAR - STAYING ALIVE", [
        "  Something wants what you are building, in every act. TAB to the",
        "  WAR panel and build FORCE to stay ahead of PRESSURE.",
        "",
        "  While pressure is higher than your force, INTEGRITY falls, and",
        "  at zero the run is over. It shows on the main HUD once it starts",
        "  slipping, with how long you have. It is survivable. It is also",
        "  genuinely losable, so do not leave it until the warning.",
    ]),
    ("KEYS", [
        "  TAB     cycle the panel. OPS is the act you are in; the rest",
        "          are WAR, R&D, PROJ, SYS, and BENCH, CRYPT and MKT once",
        "          you have researched them. The footer always shows the",
        "          keys for whichever panel is up.",
        "  UP/DOWN pick in whatever list is in front of you.",
        "  ENTER   act on what you picked. Every list works this way:",
        "          projects, defenders, research, attacks, coins.",
        "  LEFT    adjust the thing you picked - the chip price, a dial,",
        "  RIGHT   a firmware slot.",
        "  1-8     take a project. Reserved: it does that on every tab,",
        "          so you never have to leave what you are looking at.",
        "  x       cycle the buy multiplier, up to MAX",
        "  SPACE   etch a wafer by hand, in any act",
        "  c / u   fire the compute burst / spend entropy upgrading it",
        "  - + 0   shrink, grow, or refit the HUD to the terminal",
        "  S / q   save / save and quit.  ESC opens the menu.",
        "",
        "  The game keeps running while you read this.",
    ]),
]


def install(api):
    for heading, lines in SECTIONS:
        api.help_section(heading, lines)
